'use strict';
const $=id=>document.getElementById(id);
let current=0,selected=null;
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function box(title,text,cls=''){const b=el('section',undefined,'box '+cls);b.append(el('h3',title),el('p',text));return b;}
function listBox(title,questions,cls=''){const b=el('section',undefined,'box '+cls);b.append(el('h3',title));const l=el('ol');questions.forEach(q=>l.append(el('li',q)));b.append(l);return b;}
function renderNav(){const q=$('search').value.toLowerCase().trim();$('objections').replaceChildren();let count=0;PLAYBOOK.forEach((item,i)=>{if(q&&!JSON.stringify(item).toLowerCase().includes(q))return;count++;const b=el('button',undefined,'objection'+(i===current?' active':''));b.type='button';b.setAttribute('aria-pressed',String(i===current));b.append(el('span',String(i+1).padStart(2,'0'),'num'),el('span',item.title));b.onclick=()=>{current=i;selected=null;renderNav();renderDetail();if(matchMedia('(max-width:720px)').matches)$('detail').scrollIntoView({behavior:'auto',block:'start'});};$('objections').append(b);});$('count').textContent=count?`${count} matching objection${count===1?'':'s'}`:'No matching objections. Try another keyword.';}
function renderDetail(){const item=PLAYBOOK[current],d=$('detail');d.replaceChildren();d.append(el('span','START HERE · ACKNOWLEDGE & DISCOVER','step'),el('h2',item.title));const opening=el('div',undefined,'opening');opening.append(box('Acknowledgement',item.ack),box('Opening discovery question',item.discovery,'discovery'));d.append(opening);if(item.extra.length)d.append(listBox('Identify the previous campaign first',item.extra,'discovery'));d.append(el('p','Listen to the merchant’s answer, then choose the matching scenario.','hint'));const tabs=el('div',undefined,'tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Response scenarios');item.scenarios.forEach((s,i)=>{const b=el('button',undefined,'tab');b.id=`tab-${i}`;b.type='button';b.setAttribute('role','tab');b.setAttribute('aria-selected',String(selected===i));b.setAttribute('aria-controls','scenario-panel');b.append(el('span',`SCENARIO ${s.letter}`),el('strong',s.title));b.onclick=()=>{selected=i;renderDetail();$(`tab-${i}`).focus();};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();selected=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;renderDetail();$(`tab-${selected}`).focus();};tabs.append(b);});d.append(tabs);const panel=el('div');panel.id='scenario-panel';if(selected===null){panel.append(box('Choose a scenario','Select A, B, or C above based on what the merchant actually tells you. If none fits, keep exploring their concern.'));}else{panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',`tab-${selected}`);const s=item.scenarios[selected];const grid=el('div',undefined,'response-grid');grid.append(box('01 · Acknowledge the concern',s.ack),listBox('02 · Follow-up discovery',s.questions,'discovery'),box('03 · Confirm understanding',s.confirm),box('04 · Address the concern',s.rebuttal));panel.append(grid,box('05 · Closing / next step',s.closing,'closing'));const actions=el('div',undefined,'actions');const copy=el('button','Copy response path','copy');copy.onclick=async()=>{const text=[item.title,'Acknowledgement: '+item.ack,'Opening discovery: '+item.discovery,...item.extra,`Scenario ${s.letter}: ${s.title}`,s.ack,...s.questions,s.confirm,s.rebuttal,s.closing].join('\n\n');try{await navigator.clipboard.writeText(text);$('status').textContent='Response path copied.';}catch{$('status').textContent='Clipboard unavailable. Select and copy the response text manually.';}setTimeout(()=>{$('status').textContent='';},4000);};actions.append(el('p','Use only the questions you need. Give the merchant time to respond.'),copy);panel.append(actions);}d.append(panel);}
$('search').addEventListener('input',renderNav);
$('help').onclick=()=>{const open=$('instructions').hidden;$('instructions').hidden=!open;$('help').setAttribute('aria-expanded',String(open));};
renderNav();renderDetail();
